import typing

from aiomodels.response_formats.json_schema_response_format import JsonSchemaResponseFormat
from aiomodels.response_formats.text_response_format import TextResponseFormat

ResponseFormat = typing.Union[TextResponseFormat, JsonSchemaResponseFormat]
